version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_best_course_ever
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  petrakov-otus-best-course-ever:
    build: .
    container_name: petrakov-otus-best-course-ever
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://${MONGODB_LOGIN}:${MONGODB_PASS}@mongodb:27017/courseDB?authSource=admin
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      - mongodb
    networks:
      - app_network
    restart: on-failure

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge